### ISSUE TITLE
learn --fail-fast

### ISSUE THREAD

**Issue by amjack59** [learn-co-curriculum/array-CRUD-lab#13]
I tried to use the "learn --fail-fast" command in the terminal to execute the tests one at a time as per the read me file instructions and it does not work. I entered it literally: learn --fail-fast 

Can you give me an explanation of what I was doing wrong, or is this still a valid command?

**Comment by mendelB** [comment]
@amjack59 Thanks for raising this issue! This has since been fixed. Run `gem update learn-co` whixh will update the learn gem and allow you to run `learn` with the `--fail-fast` flag

**Comment by amjack59** [comment]
Thanks as always for looking into the issues and making a fix. I finished
the lab completing all parts and then running learn against everything at
once. It wasnt the intention of the --fail-fast flag but I could not wait
to progress. Thanks again anyway for fixing it for others.

On Mon, May 23, 2016 at 3:29 PM, Mendel Blesofsky <notifications@github.com>
wrote:

> @amjack59 <https://github.com/amjack59> Thanks for raising this issue!
> This has since been fixed. Run gem update learn-co whixh will update the
> learn gem and allow you to run learn with the --fail-fast flag
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/learn-co-curriculum/array-CRUD-lab/issues/13#issuecomment-221115286>
>



-- 
Jack Woodward
