### ISSUE TITLE
Lab will not open in IDE or submit through bash

### ISSUE THREAD

**Issue by Majick333** [learn-co-curriculum/array-CRUD-lab#20]
This lab will not open with the "open IDE" link.  When cloned and opened from github through SSH, it will not allow me to run learn commit.  Attached are the screenshots for the errors shown.

<img width="278" alt="Screen Shot 2019-10-18 at 9 08 39 PM" src="https://user-images.githubusercontent.com/49007990/67136417-7e4b8d80-f1eb-11e9-90a5-a57be5b6b304.png">
<img width="1058" alt="Screen Shot 2019-10-18 at 9 03 50 PM" src="https://user-images.githubusercontent.com/49007990/67136398-53613980-f1eb-11e9-9ae0-c5c2c6bf3d04.png">
<img width="1074" alt="Screen Shot 2019-10-18 at 9 07 20 PM" src="https://user-images.githubusercontent.com/49007990/67136399-53613980-f1eb-11e9-95d8-5eea47be731d.png">

**Comment by rrcobb** [comment]
Hi there,

[Raising issues on GitHub](http://help.learn.co/improving-learn/contributing-to-lessons/raising-an-issue-with-a-lab-or-lesson) should be reserved for problems with the curriculum — not difficulties solving a lab, mistakes fixed via [a quick edit](http://help.learn.co/improving-learn/contributing-to-lessons/can-i-edit-a-lesson), or bugs with the Learn platform (such as [lights not turning green](http://help.learn.co/your-learn-account/learn-lights/lights-not-turning-green) or [IDE issues](http://help.learn.co/the-learn-ide)).

In fact, there's a great article about this very issue over in the [Learn Help Center](http://help.learn.co/). Check it out! 🎉

If you still require assistance after reading the Help Center article, pop into [Ask a Question](http://help.learn.co/ask-a-question/where-can-i-ask-a-question-about-a-lesson) (AAQ), where the [Technical Coaches](http://help.learn.co/instructional-support/receiving-course-support/who-are-the-technical-coaches) (on [supported tracks](http://help.learn.co/instructional-support/receiving-course-support/does-my-program-or-course-have-technical-coach-support)) and fellow community members can provide additional help. For some tips on how to take full advantage of AAQ, check out [this helpful article](http://help.learn.co/ask-a-question/how-to-optimize-time-in-ask-a-question) in the [Learn Help Center](http://help.learn.co/).

If, after consulting the Help Center and AAQ, you still feel that this is an issue with the curriculum itself, please reopen the issue and provide more detail about why it's a curriculum issue, the steps needed to reproduce the issue, and any additional relevant information about your development environment (local or IDE).

Thanks! 💙
